# Use uma imagem base do Node.js
FROM node:latest

# Crie e defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o arquivo package.json e package-lock.json para o diretório de trabalho
COPY ./package*.json ./

# Instale as dependências do projeto
RUN npm install

# Copie o restante dos arquivos do projeto para o diretório de trabalho
COPY . .

# Construa o projeto React
RUN npm run build

# Exponha a porta em que o servidor React irá escutar (porta 3131)
EXPOSE 3030

# Comando para iniciar a aplicação quando o contêiner for iniciado
CMD ["npm", "start"]
